# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(718, 684)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(718, 684))
        MainWindow.setMaximumSize(QtCore.QSize(718, 684))
        MainWindow.setStyleSheet("background-color: rgb(255, 247, 158);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(700, 650))
        self.frame_2.setMaximumSize(QtCore.QSize(700, 650))
        self.frame_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_4.setStyleSheet("background-color: rgb(222, 222, 144);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.txt_imgOut_path = QtWidgets.QPlainTextEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_imgOut_path.sizePolicy().hasHeightForWidth())
        self.txt_imgOut_path.setSizePolicy(sizePolicy)
        self.txt_imgOut_path.setMinimumSize(QtCore.QSize(100, 40))
        self.txt_imgOut_path.setStyleSheet("background-color: rgb(255, 255, 208);")
        self.txt_imgOut_path.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.txt_imgOut_path.setFrameShadow(QtWidgets.QFrame.Plain)
        self.txt_imgOut_path.setObjectName("txt_imgOut_path")
        self.gridLayout_2.addWidget(self.txt_imgOut_path, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(125, 25))
        self.label_4.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 3, 1, 1)
        self.btn_mask_path = QtWidgets.QToolButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_mask_path.sizePolicy().hasHeightForWidth())
        self.btn_mask_path.setSizePolicy(sizePolicy)
        self.btn_mask_path.setMinimumSize(QtCore.QSize(25, 25))
        self.btn_mask_path.setMaximumSize(QtCore.QSize(25, 25))
        self.btn_mask_path.setStyleSheet("background-color: rgb(89, 206, 16);")
        self.btn_mask_path.setObjectName("btn_mask_path")
        self.gridLayout_2.addWidget(self.btn_mask_path, 0, 5, 1, 1)
        self.txt_img_path = QtWidgets.QPlainTextEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_img_path.sizePolicy().hasHeightForWidth())
        self.txt_img_path.setSizePolicy(sizePolicy)
        self.txt_img_path.setMinimumSize(QtCore.QSize(100, 40))
        self.txt_img_path.setStyleSheet("background-color: rgb(255, 255, 208);")
        self.txt_img_path.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.txt_img_path.setFrameShadow(QtWidgets.QFrame.Plain)
        self.txt_img_path.setObjectName("txt_img_path")
        self.gridLayout_2.addWidget(self.txt_img_path, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(125, 25))
        self.label.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.txt_mask_path = QtWidgets.QPlainTextEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_mask_path.sizePolicy().hasHeightForWidth())
        self.txt_mask_path.setSizePolicy(sizePolicy)
        self.txt_mask_path.setMinimumSize(QtCore.QSize(100, 40))
        self.txt_mask_path.setStyleSheet("background-color: rgb(255, 255, 208);")
        self.txt_mask_path.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.txt_mask_path.setFrameShadow(QtWidgets.QFrame.Plain)
        self.txt_mask_path.setObjectName("txt_mask_path")
        self.gridLayout_2.addWidget(self.txt_mask_path, 0, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(125, 25))
        self.label_3.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 3, 1, 1)
        self.btn_maskOut_path = QtWidgets.QToolButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_maskOut_path.sizePolicy().hasHeightForWidth())
        self.btn_maskOut_path.setSizePolicy(sizePolicy)
        self.btn_maskOut_path.setMinimumSize(QtCore.QSize(25, 25))
        self.btn_maskOut_path.setMaximumSize(QtCore.QSize(25, 25))
        self.btn_maskOut_path.setStyleSheet("background-color: rgb(89, 206, 16);")
        self.btn_maskOut_path.setObjectName("btn_maskOut_path")
        self.gridLayout_2.addWidget(self.btn_maskOut_path, 1, 5, 1, 1)
        self.txt_maskOut_path = QtWidgets.QPlainTextEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_maskOut_path.sizePolicy().hasHeightForWidth())
        self.txt_maskOut_path.setSizePolicy(sizePolicy)
        self.txt_maskOut_path.setMinimumSize(QtCore.QSize(100, 40))
        self.txt_maskOut_path.setStyleSheet("background-color: rgb(255, 255, 208);")
        self.txt_maskOut_path.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.txt_maskOut_path.setFrameShadow(QtWidgets.QFrame.Plain)
        self.txt_maskOut_path.setObjectName("txt_maskOut_path")
        self.gridLayout_2.addWidget(self.txt_maskOut_path, 1, 4, 1, 1)
        self.btn_img_path = QtWidgets.QToolButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_img_path.sizePolicy().hasHeightForWidth())
        self.btn_img_path.setSizePolicy(sizePolicy)
        self.btn_img_path.setMinimumSize(QtCore.QSize(25, 25))
        self.btn_img_path.setMaximumSize(QtCore.QSize(25, 25))
        self.btn_img_path.setStyleSheet("background-color: rgb(89, 206, 16);")
        self.btn_img_path.setObjectName("btn_img_path")
        self.gridLayout_2.addWidget(self.btn_img_path, 0, 2, 1, 1)
        self.btn_imgOut_path = QtWidgets.QToolButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_imgOut_path.sizePolicy().hasHeightForWidth())
        self.btn_imgOut_path.setSizePolicy(sizePolicy)
        self.btn_imgOut_path.setMinimumSize(QtCore.QSize(25, 25))
        self.btn_imgOut_path.setMaximumSize(QtCore.QSize(25, 25))
        self.btn_imgOut_path.setStyleSheet("background-color: rgb(89, 206, 16);")
        self.btn_imgOut_path.setObjectName("btn_imgOut_path")
        self.gridLayout_2.addWidget(self.btn_imgOut_path, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(125, 25))
        self.label_2.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 450))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 450))
        self.frame_5.setStyleSheet("background-color: rgb(222, 222, 144);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_8 = QtWidgets.QFrame(self.frame_5)
        self.frame_8.setStyleSheet("background-color: rgb(255, 247, 158);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.check_mask_images = QtWidgets.QCheckBox(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_mask_images.sizePolicy().hasHeightForWidth())
        self.check_mask_images.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.check_mask_images.setFont(font)
        self.check_mask_images.setChecked(True)
        self.check_mask_images.setObjectName("check_mask_images")
        self.horizontalLayout_4.addWidget(self.check_mask_images)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.frame = QtWidgets.QFrame(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("background-color: rgb(222, 222, 144);")
        self.frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.spin_expected_number = QtWidgets.QSpinBox(self.frame)
        self.spin_expected_number.setStyleSheet("background-color: rgb(255, 255, 208);")
        self.spin_expected_number.setMaximum(900000000)
        self.spin_expected_number.setProperty("value", 0)
        self.spin_expected_number.setObjectName("spin_expected_number")
        self.horizontalLayout_3.addWidget(self.spin_expected_number)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(-1, 10, -1, 20)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setVerticalSpacing(15)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.line_4 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.line_4, 1, 5, 10, 1)
        self.check_Zoom = QtWidgets.QCheckBox(self.frame)
        self.check_Zoom.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.check_Zoom.setFont(font)
        self.check_Zoom.setObjectName("check_Zoom")
        self.gridLayout_3.addWidget(self.check_Zoom, 5, 0, 1, 1)
        self.spin_Contrast_max = QtWidgets.QSpinBox(self.frame)
        self.spin_Contrast_max.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spin_Contrast_max.setFont(font)
        self.spin_Contrast_max.setStyleSheet("background-color: rgb(255, 255, 208);")
        self.spin_Contrast_max.setMaximum(10000)
        self.spin_Contrast_max.setProperty("value", 3)
        self.spin_Contrast_max.setObjectName("spin_Contrast_max")
        self.gridLayout_3.addWidget(self.spin_Contrast_max, 6, 4, 1, 1)
        self.check_Brightess = QtWidgets.QCheckBox(self.frame)
        self.check_Brightess.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.check_Brightess.setFont(font)
        self.check_Brightess.setObjectName("check_Brightess")
        self.gridLayout_3.addWidget(self.check_Brightess, 7, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 2, 1, 1)
        self.check_Rotate = QtWidgets.QCheckBox(self.frame)
        self.check_Rotate.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.check_Rotate.setFont(font)
        self.check_Rotate.setTristate(False)
        self.check_Rotate.setObjectName("check_Rotate")
        self.gridLayout_3.addWidget(self.check_Rotate, 4, 0, 1, 1)
        self.check_Noisy = QtWidgets.QCheckBox(self.frame)
        self.check_Noisy.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.check_Noisy.setFont(font)
        self.check_Noisy.setObjectName("check_Noisy")
        self.gridLayout_3.addWidget(self.check_Noisy, 9, 0, 1, 1)
        self.spin_Contrast_min = QtWidgets.QSpinBox(self.frame)
        self.spin_Contrast_min.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spin_Contrast_min.setFont(font)
        self.spin_Contrast_min.setStyleSheet("background-color: rgb(255, 255, 208);")
        self.spin_Contrast_min.setMaximum(10000)
        self.spin_Contrast_min.setProperty("value", 1)
        self.spin_Contrast_min.setObjectName("spin_Contrast_min")
        self.gridLayout_3.addWidget(self.spin_Contrast_min, 6, 2, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_3.addWidget(self.line_3, 1, 3, 1, 1)
        self.spin_Zoom_min = QtWidgets.QDoubleSpinBox(self.frame)
        self.spin_Zoom_min.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spin_Zoom_min.setFont(font)
        self.spin_Zoom_min.setStyleSheet("background-color: rgb(255, 255, 208);")
        self.spin_Zoom_min.setProperty("value", 0.8)
        self.spin_Zoom_min.setObjectName("spin_Zoom_min")
        self.gridLayout_3.addWidget(self.spin_Zoom_min, 5, 2, 1, 1)
        self.spin_Rotate_min = QtWidgets.QSpinBox(self.frame)
        self.spin_Rotate_min.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spin_Rotate_min.setFont(font)
        self.spin_Rotate_min.setStyleSheet("background-color: rgb(255, 255, 208);")
        self.spin_Rotate_min.setMinimum(-10000)
        self.spin_Rotate_min.setMaximum(10000)
        self.spin_Rotate_min.setSingleStep(1)
        self.spin_Rotate_min.setProperty("value", -5)
        self.spin_Rotate_min.setObjectName("spin_Rotate_min")
        self.gridLayout_3.addWidget(self.spin_Rotate_min, 4, 2, 1, 1)
        self.spin_Zoom_max = QtWidgets.QDoubleSpinBox(self.frame)
        self.spin_Zoom_max.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spin_Zoom_max.setFont(font)
        self.spin_Zoom_max.setStyleSheet("background-color: rgb(255, 255, 208);")
        self.spin_Zoom_max.setProperty("value", 1.2)
        self.spin_Zoom_max.setObjectName("spin_Zoom_max")
        self.gridLayout_3.addWidget(self.spin_Zoom_max, 5, 4, 1, 1)
        self.spin_Rotate_max = QtWidgets.QSpinBox(self.frame)
        self.spin_Rotate_max.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spin_Rotate_max.setFont(font)
        self.spin_Rotate_max.setStyleSheet("background-color: rgb(255, 255, 208);")
        self.spin_Rotate_max.setMinimum(-10000)
        self.spin_Rotate_max.setMaximum(10000)
        self.spin_Rotate_max.setProperty("value", 6)
        self.spin_Rotate_max.setObjectName("spin_Rotate_max")
        self.gridLayout_3.addWidget(self.spin_Rotate_max, 4, 4, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_5.sizePolicy().hasHeightForWidth())
        self.line_5.setSizePolicy(sizePolicy)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_3.addWidget(self.line_5, 1, 1, 10, 1)
        self.spin_Brightness_min = QtWidgets.QDoubleSpinBox(self.frame)
        self.spin_Brightness_min.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spin_Brightness_min.setFont(font)
        self.spin_Brightness_min.setStyleSheet("background-color: rgb(255, 255, 208);")
        self.spin_Brightness_min.setProperty("value", 0.5)
        self.spin_Brightness_min.setObjectName("spin_Brightness_min")
        self.gridLayout_3.addWidget(self.spin_Brightness_min, 7, 2, 1, 1)
        self.check_Contrast = QtWidgets.QCheckBox(self.frame)
        self.check_Contrast.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.check_Contrast.setFont(font)
        self.check_Contrast.setObjectName("check_Contrast")
        self.gridLayout_3.addWidget(self.check_Contrast, 6, 0, 1, 1)
        self.spin_Brightness_max = QtWidgets.QDoubleSpinBox(self.frame)
        self.spin_Brightness_max.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spin_Brightness_max.setFont(font)
        self.spin_Brightness_max.setStyleSheet("background-color: rgb(255, 255, 208);")
        self.spin_Brightness_max.setProperty("value", 3.0)
        self.spin_Brightness_max.setObjectName("spin_Brightness_max")
        self.gridLayout_3.addWidget(self.spin_Brightness_max, 7, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setMinimumSize(QtCore.QSize(110, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 4, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 2, 2, 1, 3)
        self.check_pad = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.check_pad.setFont(font)
        self.check_pad.setObjectName("check_pad")
        self.gridLayout_3.addWidget(self.check_pad, 8, 0, 1, 1)
        self.check_fft2d = QtWidgets.QCheckBox(self.frame)
        self.check_fft2d.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.check_fft2d.setFont(font)
        self.check_fft2d.setObjectName("check_fft2d")
        self.gridLayout_3.addWidget(self.check_fft2d, 9, 2, 1, 1)
        self.spin_pad_min = QtWidgets.QDoubleSpinBox(self.frame)
        self.spin_pad_min.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spin_pad_min.setFont(font)
        self.spin_pad_min.setStyleSheet("background-color: rgb(255, 255, 208);")
        self.spin_pad_min.setProperty("value", 0.15)
        self.spin_pad_min.setObjectName("spin_pad_min")
        self.gridLayout_3.addWidget(self.spin_pad_min, 8, 2, 1, 1)
        self.spin_pad_max = QtWidgets.QDoubleSpinBox(self.frame)
        self.spin_pad_max.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spin_pad_max.setFont(font)
        self.spin_pad_max.setStyleSheet("background-color: rgb(255, 255, 208);")
        self.spin_pad_max.setProperty("value", 0.3)
        self.spin_pad_max.setObjectName("spin_pad_max")
        self.gridLayout_3.addWidget(self.spin_pad_max, 8, 4, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_preview = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_preview.setFont(font)
        self.btn_preview.setStyleSheet("background-color: rgb(89, 206, 16);")
        self.btn_preview.setObjectName("btn_preview")
        self.verticalLayout_3.addWidget(self.btn_preview)
        self.btn_save = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_save.setFont(font)
        self.btn_save.setStyleSheet("background-color: rgb(89, 206, 16);")
        self.btn_save.setObjectName("btn_save")
        self.verticalLayout_3.addWidget(self.btn_save)
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setEnabled(False)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_8.addWidget(self.frame)
        self.horizontalLayout_5.addWidget(self.frame_8)
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setStyleSheet("background-color: rgb(255, 247, 158);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.listView = QtWidgets.QListWidget(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView.sizePolicy().hasHeightForWidth())
        self.listView.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(12)
        self.listView.setFont(font)
        self.listView.setStyleSheet("background-color: rgb(222, 222, 144);")
        self.listView.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.listView.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.listView.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listView.setObjectName("listView")
        self.verticalLayout_7.addWidget(self.listView)
        self.horizontalLayout_5.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_6.setStyleSheet("background-color: rgb(222, 222, 144);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLinkButton.sizePolicy().hasHeightForWidth())
        self.commandLinkButton.setSizePolicy(sizePolicy)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.horizontalLayout_6.addWidget(self.commandLinkButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.btn_start = QtWidgets.QPushButton(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_start.sizePolicy().hasHeightForWidth())
        self.btn_start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_start.setFont(font)
        self.btn_start.setStyleSheet("background-color: rgb(89, 206, 16);")
        self.btn_start.setObjectName("btn_start")
        self.horizontalLayout_6.addWidget(self.btn_start)
        self.verticalLayout.addWidget(self.frame_6)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 3)
        self.verticalLayout.setStretch(2, 1)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout.addWidget(self.frame_3, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Output Folder Path"))
        self.btn_mask_path.setText(_translate("MainWindow", "..."))
        self.label.setText(_translate("MainWindow", "Image Folder Path"))
        self.label_3.setText(_translate("MainWindow", "Mask Folder Path"))
        self.btn_maskOut_path.setText(_translate("MainWindow", "..."))
        self.btn_img_path.setText(_translate("MainWindow", "..."))
        self.btn_imgOut_path.setText(_translate("MainWindow", "..."))
        self.label_2.setText(_translate("MainWindow", "Output Folder Path"))
        self.check_mask_images.setText(_translate("MainWindow", "Include Mask Images"))
        self.label_8.setText(_translate("MainWindow", "Expected Number of Images"))
        self.check_Zoom.setText(_translate("MainWindow", "Zoom"))
        self.check_Brightess.setText(_translate("MainWindow", "Brightness"))
        self.label_5.setText(_translate("MainWindow", "Minimum Value"))
        self.check_Rotate.setText(_translate("MainWindow", "Rotate"))
        self.check_Noisy.setText(_translate("MainWindow", "Noisy"))
        self.check_Contrast.setText(_translate("MainWindow", "Contrast"))
        self.label_6.setText(_translate("MainWindow", "Maximum Value"))
        self.check_pad.setText(_translate("MainWindow", "Pad"))
        self.check_fft2d.setText(_translate("MainWindow", "fft2d"))
        self.btn_preview.setText(_translate("MainWindow", "Preview"))
        self.btn_save.setText(_translate("MainWindow", "Save Changes"))
        self.progressBar.setFormat(_translate("MainWindow", "%p%"))
        self.label_7.setText(_translate("MainWindow", "Settings Information"))
        self.commandLinkButton.setText(_translate("MainWindow", "Help"))
        self.btn_start.setText(_translate("MainWindow", "Augmentation Start"))

